title: 鸟岛与少年
description: 清华大学实践支队官方网站
baseurl: ""
url: "https://zf-li23.github.io/tsinghua_birdisland.github.io/

theme: minima
plugins:
  - jekyll-feed

collections:
  docs:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: base
