title: 鸟岛与少年
description: 清华大学实践支队官方网站
baseurl: "" 
url: "https://zf-li23.github.io/tsinghua_birdisland.github.io"

# Jekyll设置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from  # 添加重定向插件

# 自定义设置
collections:
  docs:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: base

# 添加重定向规则
defaults:
  - scope:
      path: "about"
    values:
      redirect_from: "/about"
  - scope:
      path: "species"
    values:
      redirect_from: "/species"
  - scope:
      path: "reports"
    values:
      redirect_from: "/reports"
  - scope:
      path: "records"
    values:
      redirect_from: "/records"
  - scope:
      path: "contact"
    values:
      redirect_from: "/contact"
